export const actionTypes = ['A1-Ciclos Formativos', 'A2-Acciones Socioambientales', 'A3-Emprendimientos', 'A4-Redes y eventos'];
export const actionsA1 = ["Ciclos formativos en acción socioambiental /ciberactivismo","Salidas de campo / actividades al aire libre"];
export const actionsA2 = ["Acciones en áreas públicas","Festival, desfiles, marchas, rodadas, campañas de arte", "Reforestacion / restauracion", "Reuniones con autoridades locales"];
export const actionsA3 = ["Ciclo formativo moda sustentable", "Ciclo formativo reuso productivo", "Ciclo formativo ecoturismo", "Ferias de emprendimiento sostenbile"];
export const actionsA4 = ["Formacion y trabajo en redes","Monitoreo equipos locales", "Campañas de ciberactivismo", "Encuentros juveniles"];
export const localidades = ["Delta Amacuro", "Carabobo", "Distrito Capital"];
export const tipoComunidad = ["Rural","Indígena", "Urbana"];
export const organizaciones = ["Es baratao", "Redsoc", "Fundacion Tierra Viva", "Fundacion Impronta", "Todos por el futuro", "Reusamas", "Ciudad Lab"];
export const VIOLET = 'rgba(95, 64, 145, 0.5)';
export const YELLOW = 'rgba(246, 191, 0, 0.6)'
export const GREEN = 'rgba(167, 203, 69, 0.6)';
export const BLUE = 'rgba(16, 159, 153, 0.6)';
export const ORANGE = 'rgba(240, 144, 51, 0.6)';
export const DARKBLUE = 'rgba(0, 0, 245, 0.6)';
export const PINK = 'rgba(244, 194, 194, 0.6)';
export const datosImp = ["nro_participantes","nro_pob_lgbtiq", "nro_mujeres", "nro_pob_ind","nro_pob_rural"];